// webui/src/App.svelte
<script>
  import { onMount } from 'svelte';
  import { exec } from 'kernelsu';
  import locate from './locate.json';
  import './app.css';

  const DEFAULT_CONFIG = {
    moduledir: '/data/adb/modules',
    tempdir: '',
    mountsource: 'KSU',
    logfile: '/data/adb/meta-hybrid/daemon.log',
    verbose: false,
    partitions: []
  };

  const CONFIG_PATH = '/data/adb/meta-hybrid/config.conf';
  const HYBRID_CONFIG_PATH = "/data/adb/meta-hybrid/rules.conf";

  // i18n
  let lang = 'en';
  $: L = locate[lang];
  
  // Autoload lang 
  const availableLanguages = Object.keys(locate).map(code => ({
    code,
    name: locate[code]?.lang?.display || code.toUpperCase()
  }));

  let langDropdownOpen = false;

  function toggleLangDropdown() {
    langDropdownOpen = !langDropdownOpen;
  }

  function selectLanguage(newLang) {
    lang = newLang;
    langDropdownOpen = false;
    if (typeof window !== 'undefined') {
      window.localStorage.setItem('mm-lang', newLang);
    }
  }

  function handleClickOutside(event) {
    const dropdown = event.target.closest('.lang-dropdown');
    if (!dropdown && langDropdownOpen) {
      langDropdownOpen = false;
    }
  }

  // tabs
  let activeTab = 'config';
  let isSwitching = false;

  function switchTab(tab) {
    if (tab === activeTab || isSwitching) return;
    isSwitching = true;
    setTimeout(() => {
      activeTab = tab;
      isSwitching = false;
    }, 300);
  }

  // --- config state ---
  let config = { ...DEFAULT_CONFIG };
  let configLoading = false;
  let configSaving = false;
  let configMessage = null;

  // --- rules state ---
  let rules = []; // { path: string, mode: 'overlay'|'bind' }
  let rulesLoading = false;
  let rulesSaving = false;
  let rulesMessage = null;
  // Module selector for import
  let showModuleSelector = false;
  let modulesList = [];
  let scanningModules = false;

  // --- log state ---
  let logSelection = 'current';
  let logContent = '';
  let logLoading = false;
  let logError = null;

  // partitions input
  let partitionInput = '';

  // modules state
  let modules = [];
  let modulesLoading = false;
  let modulesError = null;

  // helpers
  function isTrueValue(v) {
    const s = v.trim().toLowerCase();
    return s === '1' || s === 'true' || s === 'yes' || s === 'on';
  }

  function parseKvConfig(text) {
    try {
      const result = { ...DEFAULT_CONFIG };
      const lines = text.split('\n');
      for (let line of lines) {
        line = line.trim();
        if (!line || line.startsWith('#')) continue;
        const eqIndex = line.indexOf('=');
        if (eqIndex < 0) continue;
        let key = line.slice(0, eqIndex).trim();
        let value = line.slice(eqIndex + 1).trim();
        if (!key || !value) continue;
        switch (key) {
          case 'module_dir': result.moduledir = value; break;
          case 'temp_dir': result.tempdir = value; break;
          case 'mount_source': result.mountsource = value; break;
          case 'log_file': result.logfile = value; break;
          case 'debug': result.verbose = isTrueValue(value); break;
          case 'partitions':
            result.partitions = value.split(',').map(s => s.trim()).filter(s => s.length > 0);
            break;
        }
      }
      return result;
    } catch (e) {
      console.error('Failed to parse config:', e);
      return null;
    }
  }

  function serializeKvConfig(cfg) {
    const lines = ['# Magic Mount Configuration File', '# Generated by Web UI', ''];
    const moduleDir = cfg.moduledir || DEFAULT_CONFIG.moduledir;
    const mountSource = cfg.mountsource || DEFAULT_CONFIG.mountsource;
    const logFile = cfg.logfile || DEFAULT_CONFIG.logfile;
    lines.push(`module_dir=${moduleDir}`);
    if (cfg.tempdir) lines.push(`temp_dir=${cfg.tempdir}`);
    lines.push(`mount_source=${mountSource}`);
    if (logFile) lines.push(`log_file=${logFile}`);
    lines.push(`debug=${cfg.verbose ? 'true' : 'false'}`);
    if (cfg.partitions.length > 0) lines.push(`partitions=${cfg.partitions.join(',')}`);
    return lines.join('\n');
  }

  // --- Logic: Config ---
  async function loadConfig() {
    configLoading = true;
    configMessage = null;
    try {
      const { errno, stdout, stderr } = await exec(
        `[ -f "${CONFIG_PATH}" ] && cat "${CONFIG_PATH}" || echo ""`
      );
      if (errno !== 0) {
        console.error(stderr);
        config = { ...DEFAULT_CONFIG };
        partitionInput = '';
        configMessage = L.config.loadError;
        return;
      }
      if (!stdout.trim()) {
        config = { ...DEFAULT_CONFIG };
        partitionInput = '';
        configMessage = L.config.loadDefault;
        return;
      }
      const parsed = parseKvConfig(stdout);
      if (parsed) {
        config = parsed;
        partitionInput = parsed.partitions.join(', ');
        configMessage = L.config.loadSuccess;
      } else {
        config = { ...DEFAULT_CONFIG };
        partitionInput = '';
        configMessage = L.config.loadError;
      }
    } catch (e) {
      console.error(e);
      config = { ...DEFAULT_CONFIG };
      partitionInput = '';
      configMessage = L.config.loadError;
    } finally {
      configLoading = false;
    }
  }

  async function saveConfig() {
    configSaving = true;
    configMessage = null;
    try {
      const partitions = partitionInput.split(',').map(s => s.trim()).filter(s => s);
      const configToSave = { ...config, partitions };
      const content = serializeKvConfig(configToSave);
      const escapedContent = content.replace(/'/g, "'\\''");
      const shell = `
        mkdir -p "$(dirname "${CONFIG_PATH}")" && \
        printf '%s\n' '${escapedContent}' > "${CONFIG_PATH}"
      `;
      const { errno, stderr } = await exec(shell);
      if (errno !== 0) {
        console.error(stderr);
        configMessage = L.config.saveFailed;
      } else {
        config = configToSave;
        configMessage = L.config.saveSuccess;
      }
    } catch (e) {
      console.error(e);
      configMessage = L.config.saveError;
    } finally {
      configSaving = false;
    }
  }

  // --- Logic: Rules (移植) ---
  async function loadRules() {
    rulesLoading = true;
    rulesMessage = null;
    try {
      const { errno, stdout } = await exec(`[ -f "${HYBRID_CONFIG_PATH}" ] && cat "${HYBRID_CONFIG_PATH}" || echo ""`);
      if (errno !== 0) {
        rules = []; return;
      }
      const newRules = [];
      const lines = stdout.split("\n");
      for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith("#")) continue;
        const parts = trimmed.split("|");
        if (parts.length === 2) {
          newRules.push({ path: parts[0].trim(), mode: parts[1].trim().toLowerCase() });
        }
      }
      rules = newRules;
    } catch {
      rules = [];
    } finally {
      rulesLoading = false;
    }
  }

  async function saveRules() {
    rulesSaving = true;
    rulesMessage = null;
    try {
      let content = "# Hybrid Mount Rules\n# Path|Mode\n\n";
      for (const r of rules) {
        if (r.path.trim()) content += `${r.path.trim()}|${r.mode}\n`;
      }
      const escaped = content.replace(/'/g, "'\\''");
      const shell = `mkdir -p "$(dirname "${HYBRID_CONFIG_PATH}")" && printf '%s\n' '${escaped}' > "${HYBRID_CONFIG_PATH}"`;
      const { errno } = await exec(shell);
      if (errno !== 0) rulesMessage = L.rules.saveFailed;
      else rulesMessage = L.rules.saveSuccess;
    } catch {
      rulesMessage = L.rules.saveFailed;
    } finally {
      rulesSaving = false;
    }
  }

  // --- Logic: Import Modules (移植) ---
  async function fetchModules() {
    scanningModules = true;
    showModuleSelector = true;
    modulesList = [];
    try {
      const { stdout } = await exec(`ls -1 /data/adb/modules`);
      const mods = stdout.split("\n").map(s => s.trim()).filter(s => s && s !== "meta-hybrid" && s !== "mountify");
      modulesList = mods;
    } catch (e) {
      console.error(e);
    } finally {
      scanningModules = false;
    }
  }

  async function importModuleRules(moduleId) {
    scanningModules = true;
    try {
      const base = `/data/adb/modules/${moduleId}`;
      // Find directories depth 1-3 (system/app/xxx)
      const cmd = `find "${base}/system" -mindepth 1 -maxdepth 3 -type d`;
      const { stdout } = await exec(cmd);
      
      const paths = stdout.split("\n").map(s => s.trim()).filter(s => s);
      const newRules = [...rules];
      let count = 0;

      paths.forEach(fullPath => {
        // Convert /data/adb/modules/xyz/system/app/abc -> /system/app/abc
        const relativePath = fullPath.substring(base.length);
        if (relativePath === "/system") return;

        if (!newRules.find(r => r.path === relativePath)) {
          newRules.push({ path: relativePath, mode: "overlay" });
          count++;
        }
      });

      rules = newRules;
      rulesMessage = L.rules.importResult.replace("{0}", count.toString()).replace("{1}", moduleId);
      showModuleSelector = false;
    } catch (e) {
      console.error(e);
      rulesMessage = "Failed to scan module";
    } finally {
      scanningModules = false;
    }
  }

  function addRule() {
    rules = [...rules, { path: "", mode: "overlay" }];
  }

  function deleteRule(index) {
    rules = rules.filter((_, i) => i !== index);
  }

  // --- Logic: Logs ---
  async function loadLog() {
    logLoading = true;
    logError = null;
    logContent = '';
    try {
      const basePath = config.logfile || DEFAULT_CONFIG.logfile;
      const fullPath = logSelection === 'current' ? basePath : `${basePath}.old`;
      const { errno, stdout, stderr } = await exec(
        `[ -f "${fullPath}" ] && cat "${fullPath}" || echo "Log file not found"`
      );
      if (errno !== 0) {
        console.error(stderr);
        logError = L.logs.readFailed + ` (errno=${errno})`;
      } else {
        logContent = stdout || '';
      }
    } catch (e) {
      console.error(e);
      logError = L.logs.readException;
    } finally {
      logLoading = false;
    }
  }

  // --- Logic: Modules Tab ---
  async function loadModules() {
    modulesLoading = true;
    modulesError = null;
    modules = [];
    try {
      const moduleDir = config.moduledir || DEFAULT_CONFIG.moduledir;
      const shell = `
        MOD_DIR="${moduleDir}"
        [ -d "$MOD_DIR" ] || exit 0
        for m in "$MOD_DIR"/*; do
          [ -d "$m" ] || continue
          [ -d "$m/system" ] || continue
          name="$(basename "$m")"
          disabled=0
          skip=0
          if [ -e "$m/disable" ] || [ -e "$m/remove" ]; then
            disabled=1
          fi
          if [ -e "$m/skip_mount" ]; then
            skip=1
          fi
          printf '%s|%s|%s\n' "$name" "$disabled" "$skip"
        done
      `;
      const { errno, stdout, stderr } = await exec(shell);
      if (errno !== 0) {
        console.error(stderr);
        modulesError = L.modules.loadError;
        return;
      }
      const lines = stdout.split('\n').map(l => l.trim()).filter(l => l.length > 0);
      modules = lines.map(line => {
        const [name, disabledStr, skipStr] = line.split('|');
        return {
          name: name || '(unknown)',
          disabledByFlag: disabledStr === '1',
          skipMount: skipStr === '1',
          toggling: false
        };
      });
    } catch (e) {
      console.error(e);
      modulesError = L.modules.loadError;
    } finally {
      modulesLoading = false;
    }
  }

  async function toggleSkipMount(mod) {
    if (mod.disabledByFlag) return;
    const moduleDir = config.moduledir || DEFAULT_CONFIG.moduledir;
    const modulePath = `${moduleDir}/${mod.name}`;
    modules = modules.map(m =>
      m.name === mod.name ? { ...m, toggling: true, error: undefined } : m
    );
    try {
      const shell = mod.skipMount
        ? `rm -f "${modulePath}/skip_mount"`
        : `touch "${modulePath}/skip_mount"`;
      const { errno, stderr } = await exec(shell);
      if (errno !== 0) {
        console.error(stderr);
        modules = modules.map(m =>
          m.name === mod.name ? { ...m, toggling: false, error: L.modules.toggleError } : m
        );
      } else {
        modules = modules.map(m =>
          m.name === mod.name
            ? { ...m, skipMount: !m.skipMount, toggling: false, error: undefined }
            : m
        );
      }
    } catch (e) {
      console.error(e);
      modules = modules.map(m =>
        m.name === mod.name ? { ...m, toggling: false, error: L.modules.toggleError } : m
      );
    }
  }

  // --- Effects ---
  onMount(() => {
    if (typeof window !== 'undefined') {
      const saved = window.localStorage.getItem('mm-lang');
      if (saved && locate[saved]) {
        lang = saved;
      }
      window.addEventListener('click', handleClickOutside);
      return () => {
        window.removeEventListener('click', handleClickOutside);
      };
    }
    loadConfig();
  });

  // reactive statements for tab changes
  let configLoaded = false;
  $: if (activeTab === 'config' && !configLoaded ) {
    loadConfig().then(() => { configLoaded = true; });
  }
  
  // 新增：Rules Tab 激活时加载
  $: if (activeTab === 'rules') {
    loadRules();
  }

  $: if (activeTab === 'log') {
    loadLog();
  }

  $: if (activeTab === 'module') {
    loadModules();
  }

  $: effectiveModuleDir = config.moduledir || DEFAULT_CONFIG.moduledir;
</script>

<div class="app-root">
  <div class="top-bar">
    <div class="title">Magic Mount</div>
    
    <div class="lang-dropdown">
      <button 
        type="button" 
        class="lang-select" 
        on:click|stopPropagation={toggleLangDropdown}
      >
        {availableLanguages.find(l => l.code === lang)?.name || lang}
        <span class="arrow {langDropdownOpen ? 'open' : ''}">▼</span>
      </button>
      
      {#if langDropdownOpen}
        <div class="lang-menu">
          {#each availableLanguages as { code, name }}
            <button
              type="button"
              class="lang-option {code === lang ? 'active' : ''}"
              on:click={() => selectLanguage(code)}
            >
              {name}
            </button>
          {/each}
        </div>
      {/if}
    </div>
  </div>

  <div class="app-main">
    {#if isSwitching}
       <div class="tab-overlay">
          <div class="tab-spinner"></div>
      </div>
    {/if}

    {#key activeTab}
      {#if activeTab === 'config'}
        <div
          class="card"
          in:fade={{ duration: 180 }}
          out:fade={{ duration: 180 }}
        >
          <h2>{L.config.title}</h2>
          {#if configLoading}
            <p class="hint">Loading...</p>
          {/if}
          {#if configMessage}
            <p class="hint">{configMessage}</p>
          {/if}

          <div class="field">
            <label for="verbose-setting">{L.config.verboseLabel}</label>
             <div class="loglevel-switch" id="verbose-setting" role="group">
              <button
                type="button"
                class="lv-btn {!config.verbose ? 'active' : ''}"
                on:click|preventDefault={() => (config.verbose = false)}
              >
                {L.config.verboseOff}
              </button>
              <button
                type="button"
                class="lv-btn {config.verbose ? 'active' : ''}"
                on:click|preventDefault={() => (config.verbose = true)}
              >
                {L.config.verboseOn}
              </button>
            </div>
          </div>

          <div class="field">
            <label for="moduledir-input">{L.config.moduleDir}</label>
            <input
              id="moduledir-input"
              type="text"
              bind:value={config.moduledir}
              placeholder={DEFAULT_CONFIG.moduledir}
            />
          </div>

          <div class="field">
            <label for="tempdir-input">{L.config.tempDir}</label>
            <input
              id="tempdir-input"
              type="text"
              bind:value={config.tempdir}
              placeholder="(auto-select if empty)"
            />
          </div>

          <div class="field">
            <label for="mountsource-input">{L.config.mountSource}</label>
            <input
              id="mountsource-input"
              type="text"
              bind:value={config.mountsource}
              placeholder={DEFAULT_CONFIG.mountsource}
            />
          </div>

          <div class="field">
            <label for="logfile-input">{L.config.logFile}</label>
            <input
              id="logfile-input"
              type="text"
              bind:value={config.logfile}
              placeholder={DEFAULT_CONFIG.logfile}
            />
          </div>

          <div class="field">
            <label for="partitions-input">{L.config.partitions}</label>
            <input
              id="partitions-input"
              type="text"
              bind:value={partitionInput}
              placeholder="mi_ext,my_stock"
            />
          </div>

          <div class="actions">
            <button type="button" on:click|preventDefault={loadConfig} disabled={configLoading || configSaving}>
              {L.config.reload}
            </button>
            <button type="button" class="primary" on:click|preventDefault={saveConfig} disabled={configSaving || configLoading}>
              {configSaving ? 'Saving...' : L.config.save}
            </button>
          </div>

          <p class="path">{L.config.pathLabel}: {CONFIG_PATH}</p>
        </div>

      {:else if activeTab === 'rules'}
        <div
          class="card"
          in:fade={{ duration: 180 }}
          out:fade={{ duration: 180 }}
        >
          <h2>{L.rules.title}</h2>
          <p class="hint">{L.rules.desc}</p>
          {#if rulesLoading}<p class="hint">Loading...</p>{/if}
          {#if rulesMessage}<p class="hint">{rulesMessage}</p>{/if}

          <div class="rules-table">
            <div class="rules-header">
              <span style="flex: 2">{L.rules.pathHeader}</span>
              <span style="flex: 1">{L.rules.modeHeader}</span>
              <span style="width: 50px">{L.rules.actionHeader}</span>
            </div>
            {#each rules as rule, idx}
              <div class="rule-row">
                <input type="text" style="flex: 2" bind:value={rule.path} />
                <select style="flex: 1" bind:value={rule.mode}>
                  <option value="overlay">{L.rules.modeOverlay}</option>
                  <option value="bind">{L.rules.modeBind}</option>
                </select>
                <button class="delete-btn" on:click={() => deleteRule(idx)}>X</button>
              </div>
            {/each}
          </div>

          <div class="actions" style="flex-wrap: wrap;">
            <button on:click={addRule}>{L.rules.add}</button>
            <button on:click={fetchModules} style="background-color: #4caf50; color: white;">{L.rules.importBtn}</button>
            <div style="flex: 1"></div>
            <button on:click={loadRules}>{L.rules.reload}</button>
            <button class="primary" on:click={saveRules} disabled={rulesSaving}>
              {rulesSaving ? 'Saving...' : L.rules.save}
            </button>
          </div>

          {#if showModuleSelector}
            <div class="modal-overlay">
              <div class="modal">
                <h3>{L.rules.importTitle}</h3>
                <p class="hint">{L.rules.importDesc}</p>
                {#if scanningModules}
                  <p>{L.rules.scanning}</p>
                {:else}
                  <div class="module-list-scroll">
                    {#if modulesList.length === 0}
                      <p>{L.rules.noModules}</p>
                    {:else}
                      {#each modulesList as mod}
                        <div class="module-item" on:click={() => importModuleRules(mod)}>
                          {mod}
                        </div>
                      {/each}
                    {/if}
                  </div>
                {/if}
                <button class="close-btn" on:click={() => (showModuleSelector = false)}>{L.rules.cancel}</button>
              </div>
            </div>
          {/if}
        </div>

      {:else if activeTab === 'module'}
        <div
          class="card"
          in:fade={{ duration: 180 }}
          out:fade={{ duration: 180 }}
        >
          <h2>{L.modules.title}</h2>

          <p class="path">{L.modules.basePath}: {effectiveModuleDir}</p>

          {#if modulesError}
            <p class="error">{modulesError}</p>
          {/if}
          {#if modulesLoading && modules.length === 0}
            <p class="hint">Loading...</p>
          {/if}

          {#if !modulesLoading && modules.length === 0 && !modulesError}
            <p class="hint">{L.modules.empty}</p>
          {/if}

          {#if !modulesLoading && modules.length > 0}
            <div class="module-list">
              {#each modules as m (m.name)}
                <div class="module-row">
                  <div class="module-name">{m.name}</div>
                  <label class="switch {m.disabledByFlag ? 'disabled' : ''}">
                    <input
                      type="checkbox"
                      checked={m.disabledByFlag ? false : !m.skipMount}
                      disabled={m.disabledByFlag || m.toggling}
                      on:change={() => {
                        if (!m.disabledByFlag) toggleSkipMount(m);
                      }}
                    />
                    <span class="slider"></span>
                  </label>
                  {#if m.error}
                    <p class="error small">{m.error}</p>
                  {/if}
                </div>
              {/each}
            </div>
          {/if}

          <div class="actions" style="margin-top: 20px">
            <button type="button" on:click|preventDefault={loadModules} disabled={modulesLoading}>
              {modulesLoading ? 'Loading...' : L.modules.reload}
            </button>
          </div>
        </div>

      {:else}
        <div
          class="card"
          in:fade={{ duration: 180 }}
          out:fade={{ duration: 180 }}
        >
          <h2>{L.logs.title}</h2>

          <div class="field">
            <label for="log-select">{L.logs.select}</label>
            <div class="log-select-row">
              <select id="log-select" bind:value={logSelection}>
                <option value="current">{L.logs.current}</option>
                <option value="old">{L.logs.old}</option>
              </select>

              <button type="button" class="refresh-btn" on:click|preventDefault={loadLog} disabled={logLoading}>
                {logLoading ? 'Loading...' : L.logs.refresh}
              </button>
            </div>
          </div>

          {#if logError}
            <p class="error">{logError}</p>
          {/if}

          <pre class="log-view">{logLoading && !logContent ? 'Loading...' : logContent || L.logs.empty}</pre>
        </div>
      {/if}
    {/key}
  </div>

  <div class="bottom-bar">
    <button
      type="button"
      class="tab-btn {activeTab === 'config' ? 'active' : ''}"
      on:click|preventDefault={() => switchTab('config')}
    >
      {L.tabs.config}
    </button>
    <button
      type="button"
      class="tab-btn {activeTab === 'rules' ? 'active' : ''}"
      on:click|preventDefault={() => switchTab('rules')}
    >
      {L.tabs.rules}
    </button>

    <button
      type="button"
      class="tab-btn {activeTab === 'module' ? 'active' : ''}"
      on:click|preventDefault={() => switchTab('module')}
    >
      {L.tabs.modules}
    </button>

    <button
      type="button"
      class="tab-btn {activeTab === 'log' ? 'active' : ''}"
      on:click|preventDefault={() => switchTab('log')}
    >
      {L.tabs.logs}
    </button>
  </div>

</div>

<style>
  /* 移植的 Rules 相关样式 */
  .rules-table {
    display: flex;
    flex-direction: column;
    gap: 8px;
    margin-bottom: 16px;
  }
  .rules-header {
    display: flex;
    gap: 8px;
    padding: 0 4px;
    font-size: 13px;
    font-weight: bold;
    color: var(--nord4);
  }
  .rule-row {
    display: flex;
    gap: 8px;
    align-items: center;
  }
  .delete-btn {
    width: 50px;
    padding: 8px 0;
    text-align: center;
    background: var(--nord11);
    color: #fff;
  }
  .delete-btn:hover {
    background: #d08770;
  }

  /* Modal Styles */
  .modal-overlay { 
    position: fixed; top: 0; left: 0; right: 0; bottom: 0; 
    background: rgba(0,0,0,0.5); 
    display: flex; justify-content: center; align-items: center; 
    z-index: 1000; 
  }
  .modal { 
    background: var(--nord1); /* 使用主题色 */
    padding: 20px; 
    border-radius: 8px; 
    width: 80%; max-width: 400px; max-height: 70vh; 
    display: flex; flex-direction: column; 
    box-shadow: 0 4px 10px rgba(0,0,0,0.3); 
    color: var(--nord6);
  }
  .module-list-scroll { 
    overflow-y: auto; flex: 1; 
    margin-bottom: 15px; 
    border: 1px solid var(--nord2); 
    border-radius: 4px; 
  }
  .module-item { 
    padding: 12px; 
    border-bottom: 1px solid var(--nord2); 
    cursor: pointer; 
  }
  .module-item:last-child { border-bottom: none; }
  .module-item:hover { background: var(--nord2); }
  .close-btn { 
    align-self: flex-end; 
    padding: 8px 16px; 
    cursor: pointer; 
  }
</style>

// webui/src/App.tsx
import React, { useEffect, useState } from "react";
import { exec } from "kernelsu";
import locate from "./locate.json";
import "./index.css";

type Lang = keyof typeof locate;
type Tab = "config" | "rules" | "log";

// --- Config Types ---
type ConfigState = {
  moduledir: string;
  tempdir: string;
  mountsource: string;
  logfile: string;
  verbose: boolean;
  partitions: string[];
};

const DEFAULT_CONFIG: ConfigState = {
  moduledir: "/data/adb/modules",
  tempdir: "",
  mountsource: "KSU",
  logfile: "/data/adb/meta-hybrid/daemon.log",
  verbose: false,
  partitions: [],
};

const CONFIG_PATH = "/data/adb/meta-hybrid/config.conf";
const HYBRID_CONFIG_PATH = "/data/adb/meta-hybrid/rules.conf";

type RuleMode = "overlay" | "bind";
type HybridRule = {
  path: string;
  mode: RuleMode;
};

const App: React.FC = () => {
  // ---------- i18n ----------
  const [lang, setLang] = useState<Lang>(() => {
    if (typeof window === "undefined") return "en";
    const saved = window.localStorage.getItem("mm-lang");
    return saved === "zh" || saved === "en" ? (saved as Lang) : "en";
  });
  const L = locate[lang];

  const handleLangChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const value = e.target.value as Lang;
    setLang(value);
    if (typeof window !== "undefined") {
      window.localStorage.setItem("mm-lang", value);
    }
  };

  // ---------- tabs ----------
  const [activeTab, setActiveTab] = useState<Tab>("config");

  // ---------- config state ----------
  const [config, setConfig] = useState<ConfigState>(DEFAULT_CONFIG);
  const [configLoading, setConfigLoading] = useState(false);
  const [configSaving, setConfigSaving] = useState(false);
  const [configMessage, setConfigMessage] = useState<string | null>(null);

  // ---------- rules state ----------
  const [rules, setRules] = useState<HybridRule[]>([]);
  const [rulesLoading, setRulesLoading] = useState(false);
  const [rulesSaving, setRulesSaving] = useState(false);
  const [rulesMessage, setRulesMessage] = useState<string | null>(null);

  // ---------- module selector state ----------
  const [showModuleSelector, setShowModuleSelector] = useState(false);
  const [modulesList, setModulesList] = useState<string[]>([]);
  const [scanningModules, setScanningModules] = useState(false);

  // ---------- log state ----------
  type LogSelection = "current" | "old";
  const [logSelection, setLogSelection] = useState<LogSelection>("current");
  const [logContent, setLogContent] = useState("");
  const [logLoading, setLogLoading] = useState(false);
  const [logError, setLogError] = useState<string | null>(null);

  // ---------- partitions input ----------
  const [partitionInput, setPartitionInput] = useState("");

  // ---------- helpers ----------
  const isTrueValue = (v: string): boolean => {
    const s = v.trim().toLowerCase();
    return s === "1" || s === "true" || s === "yes" || s === "on";
  };

  const parseKvConfig = (text: string): ConfigState | null => {
    try {
      const result: ConfigState = { ...DEFAULT_CONFIG };
      const lines = text.split("\n");
      for (let line of lines) {
        line = line.trim();
        if (!line || line.startsWith("#")) continue;
        const eqIndex = line.indexOf("=");
        if (eqIndex < 0) continue;
        let key = line.slice(0, eqIndex).trim();
        let value = line.slice(eqIndex + 1).trim();
        if (!key || !value) continue;

        switch (key) {
          case "module_dir": result.moduledir = value; break;
          case "temp_dir": result.tempdir = value; break;
          case "mount_source": result.mountsource = value; break;
          case "log_file": result.logfile = value; break;
          case "debug": result.verbose = isTrueValue(value); break;
          case "partitions":
            result.partitions = value.split(",").map((s) => s.trim()).filter((s) => s.length > 0);
            break;
        }
      }
      return result;
    } catch (e) {
      console.error(e);
      return null;
    }
  };

  const serializeKvConfig = (cfg: ConfigState): string => {
    const lines: string[] = ["# Meta Hybrid Configuration", "# Generated by Web UI", ""];
    lines.push(`module_dir=${cfg.moduledir || DEFAULT_CONFIG.moduledir}`);
    if (cfg.tempdir) lines.push(`temp_dir=${cfg.tempdir}`);
    lines.push(`mount_source=${cfg.mountsource || DEFAULT_CONFIG.mountsource}`);
    if (cfg.logfile) lines.push(`log_file=${cfg.logfile}`);
    lines.push(`debug=${cfg.verbose ? "true" : "false"}`);
    if (cfg.partitions.length > 0) lines.push(`partitions=${cfg.partitions.join(",")}`);
    return lines.join("\n");
  };

  // ---------- Logic: Config ----------
  const loadConfig = async () => {
    setConfigLoading(true);
    setConfigMessage(null);
    try {
      const { errno, stdout } = await exec(`[ -f "${CONFIG_PATH}" ] && cat "${CONFIG_PATH}" || echo ""`);
      if (errno !== 0) {
        setConfig(DEFAULT_CONFIG);
        setPartitionInput("");
        setConfigMessage(L.config.loadError);
        return;
      }
      if (!stdout.trim()) {
        setConfig(DEFAULT_CONFIG);
        setPartitionInput("");
        setConfigMessage(L.config.loadDefault);
        return;
      }
      const parsed = parseKvConfig(stdout);
      if (parsed) {
        setConfig(parsed);
        setPartitionInput(parsed.partitions.join(", "));
        setConfigMessage(L.config.loadSuccess);
      } else {
        setConfig(DEFAULT_CONFIG);
        setPartitionInput("");
        setConfigMessage(L.config.loadError);
      }
    } catch (e) {
      setConfig(DEFAULT_CONFIG);
      setConfigMessage(L.config.loadError);
    } finally {
      setConfigLoading(false);
    }
  };

  const saveConfig = async () => {
    setConfigSaving(true);
    setConfigMessage(null);
    try {
      const partitions = partitionInput.split(",").map((s) => s.trim()).filter((s) => s);
      const configToSave: ConfigState = { ...config, partitions };
      const content = serializeKvConfig(configToSave);
      const escapedContent = content.replace(/'/g, "'\\''");
      const shell = `mkdir -p "$(dirname "${CONFIG_PATH}")" && printf '%s\n' '${escapedContent}' > "${CONFIG_PATH}"`;
      const { errno, stderr } = await exec(shell);
      if (errno !== 0) {
        console.error(stderr);
        setConfigMessage(L.config.saveFailed);
      } else {
        setConfig(configToSave);
        setConfigMessage(L.config.saveSuccess);
      }
    } catch (e) {
      setConfigMessage(L.config.saveError);
    } finally {
      setConfigSaving(false);
    }
  };

  // ---------- Logic: Rules ----------
  const loadRules = async () => {
    setRulesLoading(true);
    setRulesMessage(null);
    try {
      const { errno, stdout } = await exec(`[ -f "${HYBRID_CONFIG_PATH}" ] && cat "${HYBRID_CONFIG_PATH}" || echo ""`);
      if (errno !== 0) {
        setRules([]); return;
      }
      const newRules: HybridRule[] = [];
      const lines = stdout.split("\n");
      for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith("#")) continue;
        const parts = trimmed.split("|");
        if (parts.length === 2) {
          newRules.push({ path: parts[0].trim(), mode: parts[1].trim().toLowerCase() as RuleMode });
        }
      }
      setRules(newRules);
    } catch {
      setRules([]);
    } finally {
      setRulesLoading(false);
    }
  };

  const saveRules = async () => {
    setRulesSaving(true);
    setRulesMessage(null);
    try {
      let content = "# Hybrid Mount Rules\n# Path|Mode\n\n";
      for (const r of rules) {
        if (r.path.trim()) content += `${r.path.trim()}|${r.mode}\n`;
      }
      const escaped = content.replace(/'/g, "'\\''");
      const shell = `mkdir -p "$(dirname "${HYBRID_CONFIG_PATH}")" && printf '%s\n' '${escaped}' > "${HYBRID_CONFIG_PATH}"`;
      const { errno } = await exec(shell);
      if (errno !== 0) setRulesMessage(L.rules.saveFailed);
      else setRulesMessage(L.rules.saveSuccess);
    } catch {
      setRulesMessage(L.rules.saveFailed);
    } finally {
      setRulesSaving(false);
    }
  };

  // ---------- Logic: Import Modules ----------
  const fetchModules = async () => {
    setScanningModules(true);
    setShowModuleSelector(true);
    setModulesList([]);
    try {
      const { stdout } = await exec(`ls -1 /data/adb/modules`);
      const mods = stdout.split("\n").map(s => s.trim()).filter(s => s && s !== "meta-hybrid" && s !== "mountify");
      setModulesList(mods);
    } catch (e) {
      console.error(e);
    } finally {
      setScanningModules(false);
    }
  };

  const importModuleRules = async (moduleId: string) => {
    setScanningModules(true);
    try {
      const base = `/data/adb/modules/${moduleId}`;
      // Find directories depth 1-3 (system/app/xxx)
      const cmd = `find "${base}/system" -mindepth 1 -maxdepth 3 -type d`;
      const { stdout } = await exec(cmd);
      
      const paths = stdout.split("\n").map(s => s.trim()).filter(s => s);
      const newRules = [...rules];
      let count = 0;

      paths.forEach(fullPath => {
        // Convert /data/adb/modules/xyz/system/app/abc -> /system/app/abc
        const relativePath = fullPath.substring(base.length);
        if (relativePath === "/system") return;

        if (!newRules.find(r => r.path === relativePath)) {
          newRules.push({ path: relativePath, mode: "overlay" });
          count++;
        }
      });

      setRules(newRules);
      setRulesMessage(L.rules.importResult.replace("{0}", count.toString()).replace("{1}", moduleId));
      setShowModuleSelector(false);
    } catch (e) {
      console.error(e);
      setRulesMessage("Failed to scan module");
    } finally {
      setScanningModules(false);
    }
  };

  // ---------- Logic: Logs ----------
  const loadLog = async () => {
    setLogLoading(true);
    setLogError(null);
    setLogContent("");
    try {
      const basePath = config.logfile || DEFAULT_CONFIG.logfile;
      const fullPath = logSelection === "current" ? basePath : `${basePath}.old`;
      const { errno, stdout, stderr } = await exec(`[ -f "${fullPath}" ] && cat "${fullPath}" || echo "Log not found"`);
      if (errno !== 0) setLogError(L.logs.readFailed + ` (${stderr})`);
      else setLogContent(stdout || "");
    } catch {
      setLogError(L.logs.readException);
    } finally {
      setLogLoading(false);
    }
  };

  // ---------- Effects ----------
  useEffect(() => { loadConfig(); }, []);
  useEffect(() => {
    if (activeTab === "log") loadLog();
    if (activeTab === "rules") loadRules();
  }, [activeTab, logSelection]);

  // ---------- Render ----------
  const renderConfigTab = () => (
    <div className="card">
      <h2>{L.config.title}</h2>
      {configLoading && <p className="hint">Loading...</p>}
      {configMessage && <p className="hint">{configMessage}</p>}
      <div className="field">
        <label>{L.config.verboseLabel}</label>
        <div className="loglevel-switch">
          <button className={!config.verbose ? "lv-btn active" : "lv-btn"} onClick={() => setConfig({ ...config, verbose: false })}>{L.config.verboseOff}</button>
          <button className={config.verbose ? "lv-btn active" : "lv-btn"} onClick={() => setConfig({ ...config, verbose: true })}>{L.config.verboseOn}</button>
        </div>
      </div>
      <div className="field"><label>{L.config.moduleDir}</label><input type="text" value={config.moduledir} onChange={(e) => setConfig({ ...config, moduledir: e.target.value })} /></div>
      <div className="field"><label>{L.config.mountSource}</label><input type="text" value={config.mountsource} onChange={(e) => setConfig({ ...config, mountsource: e.target.value })} /></div>
      <div className="field"><label>{L.config.logFile}</label><input type="text" value={config.logfile} onChange={(e) => setConfig({ ...config, logfile: e.target.value })} /></div>
      <div className="field"><label>{L.config.partitions}</label><input type="text" value={partitionInput} onChange={(e) => setPartitionInput(e.target.value)} placeholder="mi_ext,my_stock" /></div>
      <div className="actions">
        <button onClick={loadConfig} disabled={configLoading}>{L.config.reload}</button>
        <button className="primary" onClick={saveConfig} disabled={configSaving}>{configSaving ? "Saving..." : L.config.save}</button>
      </div>
      <p className="path">{L.config.pathLabel}: {CONFIG_PATH}</p>
    </div>
  );

  const renderRulesTab = () => (
    <div className="card">
      <h2>{L.rules.title}</h2>
      <p className="hint">{L.rules.desc}</p>
      {rulesLoading && <p className="hint">Loading...</p>}
      {rulesMessage && <p className="hint">{rulesMessage}</p>}

      <div className="rules-table">
        <div className="rules-header">
          <span style={{ flex: 2 }}>{L.rules.pathHeader}</span>
          <span style={{ flex: 1 }}>{L.rules.modeHeader}</span>
          <span style={{ width: "50px" }}>{L.rules.actionHeader}</span>
        </div>
        {rules.map((rule, idx) => (
          <div className="rule-row" key={idx}>
            <input type="text" style={{ flex: 2 }} value={rule.path} onChange={(e) => { const n = [...rules]; n[idx].path = e.target.value; setRules(n); }} />
            <select style={{ flex: 1 }} value={rule.mode} onChange={(e) => { const n = [...rules]; n[idx].mode = e.target.value as RuleMode; setRules(n); }}>
              <option value="overlay">{L.rules.modeOverlay}</option>
              <option value="bind">{L.rules.modeBind}</option>
            </select>
            <button className="delete-btn" onClick={() => setRules(rules.filter((_, i) => i !== idx))}>X</button>
          </div>
        ))}
      </div>

      <div className="actions" style={{ flexWrap: "wrap" }}>
        <button onClick={() => setRules([...rules, { path: "", mode: "overlay" }])}>{L.rules.add}</button>
        <button onClick={fetchModules} style={{ backgroundColor: "#4caf50", color: "white", border: "none" }}>{L.rules.importBtn}</button>
        <div style={{ flex: 1 }}></div>
        <button onClick={loadRules}>{L.rules.reload}</button>
        <button className="primary" onClick={saveRules} disabled={rulesSaving}>{rulesSaving ? "Saving..." : L.rules.save}</button>
      </div>

      {/* Module Selector Modal */}
      {showModuleSelector && (
        <div className="modal-overlay">
          <div className="modal">
            <h3>{L.rules.importTitle}</h3>
            <p className="hint">{L.rules.importDesc}</p>
            {scanningModules ? (
              <p>{L.rules.scanning}</p>
            ) : (
              <div className="module-list">
                {modulesList.length === 0 ? <p>{L.rules.noModules}</p> : 
                  modulesList.map(mod => (
                    <div key={mod} className="module-item" onClick={() => importModuleRules(mod)}>
                      {mod}
                    </div>
                  ))
                }
              </div>
            )}
            <button className="close-btn" onClick={() => setShowModuleSelector(false)}>{L.rules.cancel}</button>
          </div>
        </div>
      )}
    </div>
  );

  const renderLogTab = () => (
    <div className="card">
      <h2>{L.logs.title}</h2>
      <div className="field">
        <div className="log-select-row">
          <select value={logSelection} onChange={(e) => setLogSelection(e.target.value as LogSelection)}>
            <option value="current">{L.logs.current}</option>
            <option value="old">{L.logs.old}</option>
          </select>
          <button className="refresh-btn" onClick={loadLog} disabled={logLoading}>{logLoading ? "..." : L.logs.refresh}</button>
        </div>
      </div>
      {logError && <p className="error">{logError}</p>}
      <pre className="log-view">{logLoading && !logContent ? "Loading..." : logContent || L.logs.empty}</pre>
    </div>
  );

  return (
    <div className="app-root">
      <div className="top-bar">
        <div className="title">Meta Hybrid</div>
        <select className="lang-select" value={lang} onChange={handleLangChange}>
          <option value="en">English</option>
          <option value="zh">中文</option>
        </select>
      </div>
      <div className="app-main">
        {activeTab === "config" && renderConfigTab()}
        {activeTab === "rules" && renderRulesTab()}
        {activeTab === "log" && renderLogTab()}
      </div>
      <div className="bottom-bar">
        <button className={activeTab === "config" ? "tab-btn active" : "tab-btn"} onClick={() => setActiveTab("config")}>{L.tabs.config}</button>
        <button className={activeTab === "rules" ? "tab-btn active" : "tab-btn"} onClick={() => setActiveTab("rules")}>{L.tabs.rules}</button>
        <button className={activeTab === "log" ? "tab-btn active" : "tab-btn"} onClick={() => setActiveTab("log")}>{L.tabs.logs}</button>
      </div>
      
      {/* Modal Styles */}
      <style>{`
        .modal-overlay { position: fixed; top: 0; left: 0; right: 0; bottom: 0; background: rgba(0,0,0,0.5); display: flex; justify-content: center; align-items: center; z-index: 1000; }
        .modal { background: var(--card-bg); padding: 20px; border-radius: 8px; width: 80%; max-width: 400px; max-height: 70vh; display: flex; flex-direction: column; box-shadow: 0 4px 10px rgba(0,0,0,0.3); }
        .module-list { overflow-y: auto; flex: 1; margin-bottom: 15px; border: 1px solid var(--border); border-radius: 4px; }
        .module-item { padding: 12px; border-bottom: 1px solid var(--border); cursor: pointer; }
        .module-item:last-child { border-bottom: none; }
        .module-item:hover { background: var(--bg); }
        .close-btn { align-self: flex-end; padding: 8px 16px; cursor: pointer; }
        
        /* Dark mode support for inline styles */
        @media (prefers-color-scheme: dark) {
           .modal { background: #1e1e1e; color: #e0e0e0; }
           .module-item:hover { background: #333; }
        }
      `}</style>
    </div>
  );
};

export default App;
